// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlOn0XYusuwToUQGsgP5MWZd4TfZ1QUB4',
    appId: '1:968476071875:web:6bec8817d1e0dd74de0f76',
    messagingSenderId: '968476071875',
    projectId: 'courtvision-c400e',
    authDomain: 'courtvision-c400e.firebaseapp.com',
    storageBucket: 'courtvision-c400e.firebasestorage.app',
    measurementId: 'G-GGK1HVZGCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByxCVG1jUsWIFbwHdiQ6YJyLQyS1AyUDs',
    appId: '1:968476071875:android:1789e9f718ce3904de0f76',
    messagingSenderId: '968476071875',
    projectId: 'courtvision-c400e',
    storageBucket: 'courtvision-c400e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVczhoxgSWcD9TlGO8pmNJy4oPM2Kstj4',
    appId: '1:968476071875:ios:c88087a62e14d070de0f76',
    messagingSenderId: '968476071875',
    projectId: 'courtvision-c400e',
    storageBucket: 'courtvision-c400e.firebasestorage.app',
    iosBundleId: 'com.example.courtvision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVczhoxgSWcD9TlGO8pmNJy4oPM2Kstj4',
    appId: '1:968476071875:ios:c88087a62e14d070de0f76',
    messagingSenderId: '968476071875',
    projectId: 'courtvision-c400e',
    storageBucket: 'courtvision-c400e.firebasestorage.app',
    iosBundleId: 'com.example.courtvision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlOn0XYusuwToUQGsgP5MWZd4TfZ1QUB4',
    appId: '1:968476071875:web:f752dbca6bfdcf4dde0f76',
    messagingSenderId: '968476071875',
    projectId: 'courtvision-c400e',
    authDomain: 'courtvision-c400e.firebaseapp.com',
    storageBucket: 'courtvision-c400e.firebasestorage.app',
    measurementId: 'G-8NRRKVZ7NM',
  );
}
